services:
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   container_name: app_container
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - server

  # server:
  #   build: ./server
  #   container_name: server_container
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     MONGO_URI: mongodb://mongodb:27017
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: